input {
	beats {
		port => 5044
	}

	tcp {
		port => 50000
	}
}

## Add your filters / logstash plugins configuration here
filter {
	if [message] =! /^\{"log\.level":"info".*"Total metrics"/ {
		drop { }
	}
	if [container][name] == "postgres-db" {
		grok {
			match => { "message" => "%{TIMESTAMP_ISO8601:pg_timestamp} \[%{NUMBER:pg_pid}\] %{USER:pg_user}@%{WORD:pg_database}: LOG: statement: %{GREEDYDATA:pg_query}" }
			tag_on_failure => ["_grok_not_pg_statement"]
		}
	}
}


output {
	elasticsearch {
		hosts => "elasticsearch:9200"
		user => "logstash_internal"
		password => "${LOGSTASH_INTERNAL_PASSWORD}"
	}
}
